language: node_js
node_js:
- 8
before_deploy:
- openssl aes-256-cbc -K $encrypted_3e38cf0623c0_key -iv $encrypted_3e38cf0623c0_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: deploy