language: node_js
node_js:
- 8
addons:
  ssh_known_hosts: 47.98.142.75
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: deploy
before_deploy:
- openssl aes-256-cbc -K $encrypted_7c94771581e8_key -iv $encrypted_7c94771581e8_iv
  -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa